version: "3"
services: 
  auth-db:
    image: postgres:11
    container_name: auth-db
    networks:
      - my-network
    restart: always
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports: 
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - my-network
  
  product-db:
    image: postgres:11
    container_name: product-db
    restart: always
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports: 
      - "5433:5432"

  sales-db:
    image: mongo:4.4
    container_name: sales-db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=sales
    ports: 
      - "27017:27017"
      - "28017:28017"

  auth-api:
    build: './auth-api'
    container_name: auth-api
    environment:
      - PORT=8080
    ports: 
      - "8080:8080"

  product-api:
    build: './product-api'
    container_name: product-api
    environment:
      - PORT=8081
    ports: 
      - "8081:8081"

  sales-api:
    build: './sales-api'
    container_name: sales-api
    environment:
      - PORT=8082
    ports: 
      - "8082:8082"

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    ports:
      - "5672:5672"
      - "25676:25676"
      - "15672:15672"

networks:
  my-network:
    external: true
